CREATE TABLE IF NOT EXISTS usuarios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    password_hash text NOT NULL,
    rol varchar(50) NOT NULL DEFAULT 'Vendedor',
    fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS productos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_barras varchar(100) NOT NULL UNIQUE,
    nombre varchar(200) NOT NULL,
    descripcion text NOT NULL DEFAULT '',
    costo_proveedor numeric(12, 2) NOT NULL DEFAULT 0,
    precio_venta numeric(12, 2) NOT NULL DEFAULT 0,
    stock_actual numeric(12, 3) NOT NULL DEFAULT 0,
    stock_minimo numeric(12, 3) NOT NULL DEFAULT 0,
    categoria varchar(100) NOT NULL DEFAULT 'General',
    fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT productos_costos_no_negativos CHECK (costo_proveedor >= 0 AND precio_venta >= 0),
    CONSTRAINT productos_stock_no_negativo CHECK (stock_actual >= 0 AND stock_minimo >= 0)
);

CREATE TABLE IF NOT EXISTS ventas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    usuario_id integer NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    total numeric(12, 2) NOT NULL DEFAULT 0,
    fecha_venta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado varchar(30) NOT NULL DEFAULT 'Completada',
    metodo_pago varchar(80) NOT NULL DEFAULT 'Mostrador',
    CONSTRAINT ventas_total_no_negativo CHECK (total >= 0)
);

CREATE TABLE IF NOT EXISTS detalles_venta (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id integer NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
    producto_id integer NULL REFERENCES productos(id) ON DELETE SET NULL,
    cantidad numeric(12, 3) NOT NULL,
    precio_unitario numeric(12, 2) NOT NULL,
    subtotal numeric(12, 2) NOT NULL,
    CONSTRAINT detalles_cantidad_positiva CHECK (cantidad > 0),
    CONSTRAINT detalles_importes_no_negativos CHECK (precio_unitario >= 0 AND subtotal >= 0)
);

CREATE TABLE IF NOT EXISTS movimientos_inventario (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer NULL REFERENCES productos(id) ON DELETE SET NULL,
    usuario_id integer NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    tipo varchar(50) NOT NULL,
    cantidad numeric(12, 3) NOT NULL,
    fecha_movimiento timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notas text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_productos_busqueda_nombre ON productos USING btree (nombre);
CREATE INDEX IF NOT EXISTS idx_productos_categoria ON productos (categoria);
CREATE INDEX IF NOT EXISTS idx_productos_stock_bajo ON productos (stock_actual, stock_minimo);
CREATE INDEX IF NOT EXISTS idx_ventas_fecha ON ventas (fecha_venta DESC);
CREATE INDEX IF NOT EXISTS idx_detalles_venta_venta_id ON detalles_venta (venta_id);

INSERT INTO usuarios (username, password_hash, rol)
VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'SuperAdmin')
ON CONFLICT (username) DO NOTHING;
