CREATE TABLE IF NOT EXISTS cortes_caja (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_corte date NOT NULL,
    responsable varchar(120) NOT NULL,
    tickets integer NOT NULL DEFAULT 0,
    ventas_esperadas numeric(12, 2) NOT NULL DEFAULT 0,
    inversion numeric(12, 2) NOT NULL DEFAULT 0,
    utilidad numeric(12, 2) NOT NULL DEFAULT 0,
    fondo_inicial numeric(12, 2) NOT NULL DEFAULT 0,
    retiros numeric(12, 2) NOT NULL DEFAULT 0,
    efectivo_contado numeric(12, 2) NOT NULL DEFAULT 0,
    diferencia numeric(12, 2) NOT NULL DEFAULT 0,
    denominaciones jsonb NOT NULL DEFAULT '[]'::jsonb,
    notas text NOT NULL DEFAULT '',
    creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cortes_caja_fecha
    ON cortes_caja (fecha_corte DESC, creado_en DESC);
