ALTER TABLE productos
    ADD COLUMN IF NOT EXISTS imagen_url text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS tipo_venta varchar(20) NOT NULL DEFAULT 'Unidad';

ALTER TABLE detalles_venta
    ADD COLUMN IF NOT EXISTS descripcion_manual text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS tipo_articulo varchar(30) NOT NULL DEFAULT 'Inventario';

CREATE TABLE IF NOT EXISTS permisos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave varchar(80) NOT NULL UNIQUE,
    descripcion text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS usuario_permisos (
    usuario_id integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    permiso_id integer NOT NULL REFERENCES permisos(id) ON DELETE CASCADE,
    habilitado boolean NOT NULL DEFAULT true,
    PRIMARY KEY (usuario_id, permiso_id)
);

CREATE TABLE IF NOT EXISTS clientes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(180) NOT NULL,
    telefono varchar(40) NOT NULL DEFAULT '',
    correo varchar(160) NOT NULL DEFAULT '',
    notas text NOT NULL DEFAULT '',
    puntos integer NOT NULL DEFAULT 0,
    fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ventas
    ADD COLUMN IF NOT EXISTS cliente_id integer NULL REFERENCES clientes(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS efectivo_recibido numeric(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cambio_entregado numeric(12, 2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS devoluciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id integer NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
    usuario_id integer NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    motivo text NOT NULL DEFAULT '',
    total_devuelto numeric(12, 2) NOT NULL DEFAULT 0,
    fecha_devolucion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS detalles_devolucion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_id integer NOT NULL REFERENCES devoluciones(id) ON DELETE CASCADE,
    detalle_venta_id integer NULL REFERENCES detalles_venta(id) ON DELETE SET NULL,
    producto_id integer NULL REFERENCES productos(id) ON DELETE SET NULL,
    descripcion_manual text NOT NULL DEFAULT '',
    cantidad numeric(12, 3) NOT NULL,
    precio_unitario numeric(12, 2) NOT NULL,
    subtotal numeric(12, 2) NOT NULL,
    CONSTRAINT detalles_devolucion_cantidad_positiva CHECK (cantidad > 0),
    CONSTRAINT detalles_devolucion_importes_no_negativos CHECK (precio_unitario >= 0 AND subtotal >= 0)
);

CREATE TABLE IF NOT EXISTS reimpresiones_ticket (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id integer NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
    usuario_id integer NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha_reimpresion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO permisos (clave, descripcion)
VALUES
    ('ventas.abrir', 'Abrir punto de venta'),
    ('ventas.devoluciones', 'Registrar devoluciones'),
    ('ventas.reimprimir_ticket', 'Reimprimir tickets'),
    ('inventario.ver', 'Ver inventario'),
    ('inventario.editar', 'Registrar productos y modificar stock'),
    ('clientes.ver', 'Ver clientes frecuentes'),
    ('clientes.editar', 'Crear y editar clientes frecuentes'),
    ('corte.ver', 'Ver corte de caja'),
    ('usuarios.permisos', 'Administrar usuarios y permisos')
ON CONFLICT (clave) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_productos_tipo_venta ON productos (tipo_venta);
CREATE INDEX IF NOT EXISTS idx_clientes_nombre ON clientes (nombre);
CREATE INDEX IF NOT EXISTS idx_devoluciones_venta ON devoluciones (venta_id);
CREATE INDEX IF NOT EXISTS idx_reimpresiones_ticket_venta ON reimpresiones_ticket (venta_id);
