CREATE TABLE IF NOT EXISTS producto_imagenes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    orden integer NOT NULL DEFAULT 0,
    imagen_url text NOT NULL DEFAULT '',
    imagen_data bytea NULL,
    content_type varchar(100) NOT NULL DEFAULT '',
    file_name varchar(255) NOT NULL DEFAULT '',
    fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE producto_imagenes
    ADD COLUMN IF NOT EXISTS orden integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS imagen_url text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS imagen_data bytea NULL,
    ADD COLUMN IF NOT EXISTS content_type varchar(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS file_name varchar(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS fecha_actualizacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$
DECLARE
    constraint_name text;
BEGIN
    FOR constraint_name IN
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        WHERE nsp.nspname = 'public'
          AND rel.relname = 'producto_imagenes'
          AND con.contype = 'u'
          AND pg_get_constraintdef(con.oid) = 'UNIQUE (producto_id)'
    LOOP
        EXECUTE format('ALTER TABLE producto_imagenes DROP CONSTRAINT IF EXISTS %I', constraint_name);
    END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_producto_imagenes_producto_id
    ON producto_imagenes (producto_id);
CREATE INDEX IF NOT EXISTS idx_producto_imagenes_producto_orden
    ON producto_imagenes (producto_id, orden, id);

INSERT INTO producto_imagenes (producto_id, imagen_url, orden)
SELECT id, imagen_url
FROM productos
WHERE COALESCE(imagen_url, '') <> ''
  AND NOT EXISTS (
      SELECT 1
      FROM producto_imagenes pi
      WHERE pi.producto_id = productos.id
  );
