CREATE TABLE IF NOT EXISTS producto_imagenes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer NOT NULL UNIQUE REFERENCES productos(id) ON DELETE CASCADE,
    imagen_url text NOT NULL DEFAULT '',
    fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_producto_imagenes_producto_id
    ON producto_imagenes (producto_id);

INSERT INTO producto_imagenes (producto_id, imagen_url)
SELECT id, imagen_url
FROM productos
WHERE COALESCE(imagen_url, '') <> ''
ON CONFLICT (producto_id) DO UPDATE
SET imagen_url = EXCLUDED.imagen_url,
    fecha_actualizacion = CURRENT_TIMESTAMP
WHERE COALESCE(producto_imagenes.imagen_url, '') = '';
