-- Tabla de auditoría mejorada para rastrear todos los cambios
CREATE TABLE IF NOT EXISTS auditoria (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id integer NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    tabla varchar(50) NOT NULL,
    operacion varchar(20) NOT NULL, -- INSERT, UPDATE, DELETE
    registro_id integer NOT NULL,
    campo varchar(100) NULL, -- Campo modificado (para UPDATE)
    valor_anterior text NULL,
    valor_nuevo text NULL,
    descripcion text NOT NULL DEFAULT '',
    fecha_operacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address varchar(45) NULL,
    CONSTRAINT auditoria_operacion_valida CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- Índices para auditoría rápida
CREATE INDEX IF NOT EXISTS idx_auditoria_fecha ON auditoria(fecha_operacion DESC);
CREATE INDEX IF NOT EXISTS idx_auditoria_tabla ON auditoria(tabla);
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario ON auditoria(usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_registro ON auditoria(tabla, registro_id);

-- Renombrar movimientos_inventario a historial_inventario (más claro)
ALTER TABLE IF EXISTS movimientos_inventario RENAME TO historial_inventario;

-- Mejorar historial_inventario con auditoría
ALTER TABLE historial_inventario
ADD COLUMN IF NOT EXISTS usuario_registrador_id integer NULL REFERENCES usuarios(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS stock_anterior numeric(12, 3) NULL,
ADD COLUMN IF NOT EXISTS stock_nuevo numeric(12, 3) NULL,
ADD COLUMN IF NOT EXISTS razon varchar(255) NULL DEFAULT '';

-- Índices en historial_inventario
CREATE INDEX IF NOT EXISTS idx_historial_inventario_producto ON historial_inventario(producto_id);
CREATE INDEX IF NOT EXISTS idx_historial_inventario_usuario ON historial_inventario(usuario_id);
CREATE INDEX IF NOT EXISTS idx_historial_inventario_fecha ON historial_inventario(fecha_movimiento DESC);
