-- Destinatarios de los avisos por WhatsApp al registrar una venta.
-- El POS lee de aqui los numeros activos (sin recompilar la aplicacion).
-- El numero debe ir en formato internacional SIN el signo "+":
--   Mexico: 52 + 10 digitos. Ejemplo: 5212381234567

CREATE TABLE IF NOT EXISTS whatsapp_destinatarios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero varchar(20) NOT NULL,
    nombre varchar(120) NOT NULL DEFAULT '',
    activo boolean NOT NULL DEFAULT true,
    fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Ejemplo (reemplaza el numero por el real y descomenta):
-- INSERT INTO whatsapp_destinatarios (numero, nombre) VALUES ('5212381234567', 'Dueno');

-- Para activar/desactivar un destinatario sin borrarlo:
-- UPDATE whatsapp_destinatarios SET activo = false WHERE numero = '5212381234567';
