using Npgsql;

namespace RefaccionariaPOS.Services
{
    public static class ProductImageRepository
    {
        public static void AsegurarTabla(NpgsqlConnection conexion)
        {
            const string query = @"
                ALTER TABLE productos
                    ADD COLUMN IF NOT EXISTS imagen_url text NOT NULL DEFAULT '',
                    ADD COLUMN IF NOT EXISTS tipo_venta varchar(20) NOT NULL DEFAULT 'Unidad';

                CREATE TABLE IF NOT EXISTS producto_imagenes (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    producto_id integer NOT NULL UNIQUE REFERENCES productos(id) ON DELETE CASCADE,
                    imagen_url text NOT NULL DEFAULT '',
                    fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    fecha_actualizacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE INDEX IF NOT EXISTS idx_producto_imagenes_producto_id
                    ON producto_imagenes (producto_id);

                INSERT INTO producto_imagenes (producto_id, imagen_url)
                SELECT id, imagen_url
                FROM productos
                WHERE COALESCE(imagen_url, '') <> ''
                ON CONFLICT (producto_id) DO UPDATE
                SET imagen_url = EXCLUDED.imagen_url,
                    fecha_actualizacion = CURRENT_TIMESTAMP
                WHERE COALESCE(producto_imagenes.imagen_url, '') = '';";

            using NpgsqlCommand cmd = new NpgsqlCommand(query, conexion);
            cmd.ExecuteNonQuery();
        }

        public static void GuardarImagen(NpgsqlConnection conexion, int productoId, string imagenUrl)
        {
            if (string.IsNullOrWhiteSpace(imagenUrl))
            {
                using NpgsqlCommand delete = new NpgsqlCommand(
                    "DELETE FROM producto_imagenes WHERE producto_id = @productoId;",
                    conexion);
                delete.Parameters.AddWithValue("@productoId", productoId);
                delete.ExecuteNonQuery();
                return;
            }

            const string query = @"
                INSERT INTO producto_imagenes (producto_id, imagen_url)
                VALUES (@productoId, @imagenUrl)
                ON CONFLICT (producto_id) DO UPDATE
                SET imagen_url = EXCLUDED.imagen_url,
                    fecha_actualizacion = CURRENT_TIMESTAMP;";

            using NpgsqlCommand cmd = new NpgsqlCommand(query, conexion);
            cmd.Parameters.AddWithValue("@productoId", productoId);
            cmd.Parameters.AddWithValue("@imagenUrl", imagenUrl.Trim());
            cmd.ExecuteNonQuery();
        }
    }
}
