using System.Collections.Generic;
using System.Linq;
using Npgsql;
using NpgsqlTypes;

namespace RefaccionariaPOS.Services
{
    public static class ProductImageRepository
    {
        public static void AsegurarTabla(NpgsqlConnection conexion)
        {
            const string query = @"
                ALTER TABLE productos
                    ADD COLUMN IF NOT EXISTS imagen_url text NOT NULL DEFAULT '',
                    ADD COLUMN IF NOT EXISTS tipo_venta varchar(20) NOT NULL DEFAULT 'Unidad';

                CREATE TABLE IF NOT EXISTS producto_imagenes (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    producto_id integer NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
                    orden integer NOT NULL DEFAULT 0,
                    imagen_url text NOT NULL DEFAULT '',
                    imagen_data bytea NULL,
                    content_type varchar(100) NOT NULL DEFAULT '',
                    file_name varchar(255) NOT NULL DEFAULT '',
                    fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    fecha_actualizacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                ALTER TABLE producto_imagenes
                    ADD COLUMN IF NOT EXISTS orden integer NOT NULL DEFAULT 0,
                    ADD COLUMN IF NOT EXISTS imagen_url text NOT NULL DEFAULT '',
                    ADD COLUMN IF NOT EXISTS imagen_data bytea NULL,
                    ADD COLUMN IF NOT EXISTS content_type varchar(100) NOT NULL DEFAULT '',
                    ADD COLUMN IF NOT EXISTS file_name varchar(255) NOT NULL DEFAULT '',
                    ADD COLUMN IF NOT EXISTS fecha_alta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ADD COLUMN IF NOT EXISTS fecha_actualizacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

                DO $$
                DECLARE
                    constraint_name text;
                BEGIN
                    FOR constraint_name IN
                        SELECT con.conname
                        FROM pg_constraint con
                        JOIN pg_class rel ON rel.oid = con.conrelid
                        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
                        WHERE nsp.nspname = 'public'
                          AND rel.relname = 'producto_imagenes'
                          AND con.contype = 'u'
                          AND pg_get_constraintdef(con.oid) = 'UNIQUE (producto_id)'
                    LOOP
                        EXECUTE format('ALTER TABLE producto_imagenes DROP CONSTRAINT IF EXISTS %I', constraint_name);
                    END LOOP;
                END $$;

                CREATE INDEX IF NOT EXISTS idx_producto_imagenes_producto_id
                    ON producto_imagenes (producto_id);
                CREATE INDEX IF NOT EXISTS idx_producto_imagenes_producto_orden
                    ON producto_imagenes (producto_id, orden, id);

                INSERT INTO producto_imagenes (producto_id, imagen_url, orden)
                SELECT id, imagen_url
                FROM productos
                WHERE COALESCE(imagen_url, '') <> ''
                  AND NOT EXISTS (
                      SELECT 1
                      FROM producto_imagenes pi
                      WHERE pi.producto_id = productos.id
                  );";

            using NpgsqlCommand cmd = new NpgsqlCommand(query, conexion);
            cmd.ExecuteNonQuery();
        }

        public static void GuardarImagen(NpgsqlConnection conexion, int productoId, string imagenUrl)
        {
            GuardarImagen(conexion, productoId, ProductImageService.PrepararImagenParaBase(imagenUrl));
        }

        public static void GuardarImagen(NpgsqlConnection conexion, int productoId, ProductImageData imagen)
        {
            GuardarImagenes(conexion, productoId, [imagen]);
        }

        public static void GuardarImagenes(NpgsqlConnection conexion, int productoId, IReadOnlyList<ProductImageData> imagenes)
        {
            using NpgsqlCommand delete = new NpgsqlCommand(
                "DELETE FROM producto_imagenes WHERE producto_id = @productoId;",
                conexion);
            delete.Parameters.AddWithValue("@productoId", productoId);
            delete.ExecuteNonQuery();

            List<ProductImageData> imagenesValidas = imagenes
                .Where(imagen => !imagen.IsEmpty)
                .ToList();

            if (imagenesValidas.Count == 0)
            {
                return;
            }

            const string query = @"
                INSERT INTO producto_imagenes (producto_id, orden, imagen_url, imagen_data, content_type, file_name)
                VALUES (@productoId, @orden, @imagenUrl, @imagenData, @contentType, @fileName);";

            for (int index = 0; index < imagenesValidas.Count; index++)
            {
                ProductImageData imagen = imagenesValidas[index];
                using NpgsqlCommand cmd = new NpgsqlCommand(query, conexion);
                cmd.Parameters.AddWithValue("@productoId", productoId);
                cmd.Parameters.AddWithValue("@orden", index);
                cmd.Parameters.AddWithValue("@imagenUrl", imagen.Url);
                cmd.Parameters.Add("@imagenData", NpgsqlDbType.Bytea).Value = (object?)imagen.Data ?? System.DBNull.Value;
                cmd.Parameters.AddWithValue("@contentType", imagen.ContentType);
                cmd.Parameters.AddWithValue("@fileName", imagen.FileName);
                cmd.ExecuteNonQuery();
            }
        }
    }
}
